LAB/Laboratorio.rvc/Lab/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            string user = Convert.ToString(Session["usuario"]);
            if (user == "")
            {
                return RedirectToAction("Login", "Login");
            }
            return View();

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

LAB/Laboratorio.rvc/Lab/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace Lab.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login

        private BD_Lab2Entities conn = new BD_Lab2Entities();

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string user, string password)
        {

            if (!string.IsNullOrEmpty(user) && !string.IsNullOrEmpty(password))
            {
                var usuario = conn.tbUsuario.FirstOrDefault(p => p.nombreUsuario == user && p.contraseña == password);

                if (usuario != null)
                {

                    
                    Session["usuario"] = user;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }


        }
        public ActionResult CerrarSesion()
        {
            Session.Contents.RemoveAll();
            return RedirectToAction("Login", "Login");
        }
    }
}

LAB/Laboratorio.rvc/Lab/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace Lab.Controllers
{
    public class PacienteController : Controller
    {
        private BD_Lab2Entities conn = new BD_Lab2Entities();
        // GET: Paciente
        public ActionResult Busqueda(string DNI)
        {
            string user = Convert.ToString(Session["usuario"]);
            if (user == "")
            {
                return RedirectToAction("Login", "Login");
            }

            else
            {
                using (var db = new BD_Lab2Entities())
                {

                    var busqueda = from s in db.tbPaciente select s;

                    if (!String.IsNullOrEmpty(DNI))
                    {
                        busqueda = busqueda.Where(s => s.dni.Contains(DNI));
                    }
                    return View(busqueda.ToList());


                }
            }
            
        }
        

        [HttpGet]
        public ActionResult Nuevo()
        {
            ViewBag.ListaSexo = conn.tbSexo.ToList();
            return View();
            
        }
        [HttpPost]
        public ActionResult Nuevo(tbPaciente paci)
        {
            conn.tbPaciente.Add(paci);
            conn.SaveChanges();
            return RedirectToAction("Busqueda");
        }
        public ActionResult Editar(int id)

        {
            
            tbPaciente paciente = new tbPaciente();
            paciente = conn.tbPaciente.Find(id);
            ViewBag.ListaSexo = conn.tbSexo.ToList();
            return View(paciente);

            
        }
        [HttpPost]
        public ActionResult Editar(tbPaciente pacientenew)
        {
            tbPaciente paciente = new tbPaciente();
            paciente = conn.tbPaciente.Find(pacientenew.idPaciente);
            paciente.dni = pacientenew.dni;
            paciente.nombrePaciente = pacientenew.nombrePaciente;
            paciente.apellidoPaciente = pacientenew.apellidoPaciente;
            paciente.direccion = pacientenew.direccion;
            paciente.idSexo = pacientenew.idSexo;
            paciente.telefono = pacientenew.telefono;
            paciente.fechaNacimiento = pacientenew.fechaNacimiento;
            conn.SaveChanges();
            return RedirectToAction("Busqueda");

            

        }
    }
}

LAB/Laboratorio.rvc/Lab/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace Lab.Controllers
{
    public class SolicitudController : Controller
    {
        private BD_Lab2Entities conn = new BD_Lab2Entities();
        // GET: SolicitudExamen
        public ActionResult Index()
        {
            string user = Convert.ToString(Session["usuario"]);
            if (user == "")
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View(conn.tbSolicitudExamen.ToList());
            }
            
        }
        [HttpGet]
        public ActionResult Nuevo(int id)

        {
            ViewBag.id = id;
                      
            ViewBag.Examen = conn.tbExamen.ToList();
            ViewBag.Usuario = conn.tbUsuario.ToList();
            //List<tbExamen> examen = conn.tbExamen.Where(e => e.estado).ToList();

            return View();

        }
        [HttpPost]
        public ActionResult Nuevo(tbSolicitudExamen solic)
        {
            conn.tbSolicitudExamen.Add(solic);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LAB/Laboratorio.rvc/Lab/Controllers/TipoExamenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAO;

namespace Lab.Controllers
{
    public class TipoExamenController : Controller
    {

        private BD_Lab2Entities conn = new BD_Lab2Entities();
        // GET: TipoExamen
        public ActionResult Index( )
        {
            string user = Convert.ToString(Session["usuario"]);
            if (user == "")
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                return View(conn.tbExamen.ToList());
            }
        }
        [HttpGet]
        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(tbExamen exam)
        {
            conn.tbExamen.Add(exam);
            conn.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Editar(int id)
        {
            tbExamen exam = new tbExamen();
            exam = conn.tbExamen.Find(id);
            return View(exam);
        }
        [HttpPost]
        public ActionResult Editar(tbExamen examnew)
        {
            tbExamen exam = new tbExamen();
            exam = conn.tbExamen.Find(examnew.idExamen);
            exam.nombreExamen = examnew.nombreExamen;
            exam.precioUnidad = examnew.precioUnidad;
            exam.estado = examnew.estado;
            conn.SaveChanges();
            return RedirectToAction("Index");

        }


        public ActionResult Eliminar(int id)
        {
            tbExamen exam = new tbExamen();
            exam = conn.tbExamen.Find(id);
            exam.estado = false;
            conn.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

LAB/Laboratorio.rvc/Lab/Views/Login/Login.cshtml
@using DAO
@model tbUsuario
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginPage.cshtml";
}

@using (Html.BeginForm())
{
    <div class="w3l-signinform">
        <!-- container -->
        <div class="wrapper">
            <!-- main content -->
            <div class="w3l-form-info">
                <div class="w3_info">
                    <h1>Bienvenido al Laboratorio</h1>

                    <h2>Log In</h2>
                    @*<form action="Login" method="post">
                            <div class="input-group">
                                <span><i class="fa fa-user" aria-hidden="true"></i></span>
                                <input type="text" placeholder="Username" required="">
                            </div>

                            <div class="input-group two-groop">
                                <span><i class="fa fa-key" aria-hidden="true"></i></span>
                                <input type="Password" placeholder="Password" required="">
                            </div>

                            <button class="btn btn-primary btn-block" type="submit">Log In</button>
                        </form>*@

                    <div class="form-group">
                        <div class="input-group">
                            <span><i class="fa fa-user" aria-hidden="true"></i></span>


                            <input type="text" name="User" placeholder="User" class="form-control" required />
                            @*@Html.TextBoxFor(m => m.nombreUsuario, new { @class = "form-control", @id = "User", @placeholder = "User", @required = "required" })*@
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="input-group two-groop">
                            <span><i class="fa fa-key" aria-hidden="true"></i></span>
                            <input type="password" name="password" placeholder="password" class="form-control" required />


                            @*@Html.TextBoxFor(m => m.contraseña, new { @class = "form-control",@id="Password", @placeholder = "Password", @required = "required",@type="Password" })*@
                        </div>
                    </div>
                    <button class="btn btn-primary btn-block" type="submit">Log In</button>




                </div>
            </div>
            <!-- //main content -->
        </div>
        <!-- //container -->
        <!-- footer -->
        <div class="footer">
            <p>
                &copy; 2021
            </p>
        </div>
    </div>


}

LAB/Laboratorio.rvc/Lab/Views/Paciente/Busqueda.cshtml
@using DAO
@model List<tbPaciente>
@{
    ViewBag.Title = "Busqueda";
}

<h2>
    <a style="float:right;color:green" href="@Url.Action("Nuevo","Paciente")"><i class="fas fa-plus-circle"></i> </a>
    Listado Paciente
    
</h2>

@using (Html.BeginForm())
{
    <p>
        Buscar DNI : @Html.TextBox("DNI")
        <input type="submit" value="Buscar" />
    </p>
}

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>idPaciente</th>
            <th>DNI</th>
            <th>Nombre Paciente</th>
            <th>Apellido Paciente</th>
            <th>Direccion</th>
            <th>Id Sexo</th>
            <th>Telefono</th>
            <th>Fecha de Nacimiento</th>
            <th>Solicitud Examen</th>
        </tr>
    </thead>
     <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="width:50px" align="center">

                    <a href="@Url.Action("Editar","Paciente",new { id=item.idPaciente})" title="Editar" style="color:green"><i class="fas fa-edit"></i></a>
                    <a href="@Url.Action("Eliminar","Paciente",new { id=item.idPaciente})" title="Eliminar" style="color:green"><i class="fas fa-trash-alt"></i></a>
                </td>
                <td>@item.idPaciente</td>
                <td>@item.dni</td>
                <td>@item.nombrePaciente</td>
                <td>@item.apellidoPaciente</td>
                <td>@item.direccion</td>
                <td>@item.idSexo</td>
                <td>@item.telefono</td>
                <td>@item.fechaNacimiento</td>
                <td style="width:50px" align="center">

                    <a href="@Url.Action("Nuevo","Solicitud",new { id=item.idPaciente})" title="Agregar" style="color:green"><i class="fas fa-plus-circle"></i></a>

                </td>

            </tr>
        }

    </tbody>

</table>
<script type="text/javascript">
    $.getScript("/Scripts/jsPaciente.js")
        .done(function (script, textStatus) {
            //console.log(textStatus);
        })

        .fail(function (jqxhr, settings, exception) {
            console.log("fallo carga script js");
            console.log(exception);
        });
</script>

LAB/Laboratorio.rvc/Lab/Views/Paciente/Editar.cshtml
@using DAO
@model  tbPaciente
@{
    ViewBag.Title = "Editar";
}
<h2>
    <a style="float:right;color:green" href="@Url.Action("Busqueda","Paciente")"><i class="fas fa-chevron-circle-left"></i> </a>Editar Paciente
</h2>
<hr />
@using (Html.BeginForm("Editar", "Paciente", FormMethod.Post))
{

    <div class="form-group">
        <label> id Paciente</label>
        @Html.TextBoxFor(m => m.idPaciente, new { @class = "form-control", @required = "required", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label> DNI</label>
        @Html.TextBoxFor(m => m.dni, new { @class = "form-control", @required = "required", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(m => m.nombrePaciente, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Apellido</label>
        @Html.TextBoxFor(m => m.apellidoPaciente, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Direccion </label>
        @Html.TextBoxFor(m => m.direccion, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Sexo </label>
        <select name="idSexo" class="form-control" required>

            <option value="">Seleccione.....</option>

            @foreach (var item in ViewBag.ListaSexo)
            {
                <option value="@item.idSexo" @(item.idSexo == Model.idSexo ? "selected" : "")>@item.nombreSexo</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label>telefono </label>
        @Html.TextBoxFor(m => m.telefono, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Fecha Nacimiento </label>
        @Html.TextBoxFor(m => m.fechaNacimiento, new { @class = "form-control", @required = "required", @readonly = "readonly" })
    </div>



    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-success" />

    </div>
}

LAB/Laboratorio.rvc/Lab/Views/Paciente/Nuevo.cshtml
@using DAO
@model tbPaciente
@{
    ViewBag.Title = "Nuevo";
}

<h2>
<a style="float:right;color:green" href="@Url.Action("Busqueda","Paciente")"><i class="fas fa-chevron-circle-left"></i> </a>Nuevo Paciente
</h2>
<hr />

@using (Html.BeginForm("Nuevo", "Paciente", FormMethod.Post))
{

    <div class="form-group">
        <label>Numero DNI </label>

        @Html.TextBoxFor(m => m.dni, new { @class = "form-control", @required = "required", @minlength = "8", @maxlength = "8" })

    </div>
    <div class="form-group">
        <label> Nombre </label>
        @Html.TextBoxFor(m => m.nombrePaciente, new { @class = "form-control", @required = "required" })

    </div>
    <div class="form-group">
        <label> Apellido</label>
        @Html.TextBoxFor(m => m.apellidoPaciente, new { @class = "form-control", @required = "required" })

    </div>
    <div class="form-group">
        <label> Direccion </label>
        @Html.TextBoxFor(m => m.direccion, new { @class = "form-control", @required = "required" })

    </div>
    <div class="form-group">
        <label> Sexo </label>
        <select name="idSexo" class="form-control" required>
            <option value="">Seleccione.....</option>

            @foreach (var item in ViewBag.ListaSexo)
            {
                <option value="@item.idSexo">@item.nombreSexo</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label> Telefono </label>
        @Html.TextBoxFor(m => m.telefono, new { @class = "form-control", @required = "required", @minlength = "9", @maxlength = "9" })

    </div>
    <div class="form-group">
        <label> Fecha Nacimiento </label>
        @Html.TextBoxFor(m => m.fechaNacimiento, new { @class = "form-control", @required = "required", @type = "date" })

    </div>






    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-success" />

    </div>


}

LAB/Laboratorio.rvc/Lab/Views/Solicitud/Index.cshtml
@using DAO
@model List<tbSolicitudExamen>
@{
    ViewBag.Title = "Index";
}
<h2>
    Listado de Solicitud de Examenes

</h2>

<hr />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            
            <th>Id Solicitud Examen</th>
            <th>Id Paciente</th>
            <th>Id Usuario</th>
            <th>Fecha</th>
            


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>@item.idSolicitudExamen</td>
                <td>@item.idPaciente</td>
                <td>@item.idUsuario</td>
                <td>@item.fecha</td>
                
                

                   


            </tr>
        }

    </tbody>

</table>

LAB/Laboratorio.rvc/Lab/Views/Solicitud/Nuevo.cshtml
@using DAO
@model tbSolicitudExamen
@{
    ViewBag.Title = "Nuevo";
}

<h2>
    <a style="float:right;color:green" href="@Url.Action("Busqueda","Paciente")"><i class="fas fa-chevron-circle-left"></i> </a> Solicitud de Examen
</h2>
<hr />
@using (Html.BeginForm("Nuevo", "Solicitud", FormMethod.Post))
{


    <div class="form-group">
        <label> Id Paciente</label>
        @Html.TextBoxFor(m => m.idPaciente, new { @class = "form-control", @Value = ViewBag.id, @required = "required", @readonly = "readonly" })

    </div>

    <div class="form-group">
        <label> Usuario </label>
        <select name="idUsuario" class="form-control" required>
            <option value="">Seleccione.....</option>

            @foreach (var item in ViewBag.Usuario)
            {
                <option value="@item.idUsuario">@item.nombreUsuario</option>
            }
        </select>

    </div>


    <div class="form-group">
        <label> Tipo de Examen </label>
        <select name="idExamen" class="form-control" required>
            <option value="">Seleccione.....</option>

            @foreach (var item in ViewBag.Examen)
            {
                <option value="@item.idExamen">@item.nombreExamen</option>
            }
        </select>

    </div>


    <div class="form-group">
        <label>Fecha Generacion</label>
        @Html.TextBoxFor(m => m.fecha, new { @class = "form-control", @required = "required", @type = "date" })
    </div>
    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-success" />
    </div>

}

LAB/Laboratorio.rvc/Lab/Views/TipoExamen/Editar.cshtml
@using DAO
@model tbExamen
@{
    ViewBag.Title = "Editar";
}
<h2>Editar</h2>
<h2>
    <a style="float:right;color:green" href="@Url.Action("Index","TipoExamen")"><i class="fas fa-chevron-circle-left"></i> </a>Actualizar Ticket
</h2>
<hr />
@using (Html.BeginForm("Editar", "TipoExamen", FormMethod.Post))
{

    <div class="form-group">
        <label> Id Tipo de Examen</label>
        @Html.TextBoxFor(m => m.idExamen, new { @class = "form-control", @required = "required", @readonly = "readonly" })
    </div>
    <div class="form-group">
        <label>Nombre Examen</label>
        @Html.TextBoxFor(m => m.nombreExamen, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Precio</label>
        @Html.TextBoxFor(m => m.precioUnidad, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Estado</label>
        @Html.TextBoxFor(m => m.estado, new { @class = "form-control", @required = "required" })
    </div>


    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-success" />

    </div>
}

LAB/Laboratorio.rvc/Lab/Views/TipoExamen/Index.cshtml
@using DAO
@model List<tbExamen>
@{
    ViewBag.Title = "Index";
}

<h2>
    <a style="float:right;color:green" href="@Url.Action("Nuevo","TipoExamen")"><i class="fas fa-plus-circle"></i> </a>
    Listado de Tipo de Examen
</h2>
<hr />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>idExamen</th>
            <th>NombreExamen</th>
            <th>Precio</th>
            <th>estado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="width:50px" align="center">

                    <a href="@Url.Action("Editar","TipoExamen",new { id=item.idExamen})" title="Editar" style="color:green"><i class="fas fa-edit"></i></a>
                    <a href="@Url.Action("Eliminar","TipoExamen",new { id=item.idExamen})" title="Eliminar" style="color:green"><i class="fas fa-trash-alt"></i></a>
                </td>
                <td>@item.idExamen</td>
                <td>@item.nombreExamen</td>
                <td>@item.precioUnidad</td>
                <td>@item.estado</td>

            </tr>
        }

    </tbody>

</table>

LAB/Laboratorio.rvc/Lab/Views/TipoExamen/Nuevo.cshtml
@using DAO
@model tbExamen
@{
    ViewBag.Title = "Nuevo";
}
<h2>
    <a style="float:right;color:green" href="@Url.Action("Index","TipoExamen")"><i class="fas fa-chevron-circle-left"></i> </a>Nuevo tipo de examen
</h2>
<hr />

@using (Html.BeginForm("Nuevo", "TipoExamen", FormMethod.Post))
{

    <div class="form-group">
        <label>Nombre Examen </label>
        @Html.TextBoxFor(m => m.nombreExamen, new { @class = "form-control", @required = "required" })

    </div>
    <div class="form-group">
        <label> Precio </label>
        @Html.TextBoxFor(m => m.precioUnidad, new { @class = "form-control", @required = "required" })

    </div>
    <div class="form-group">
        <label> Estado </label>
        @Html.TextBoxFor(m => m.estado, new { @class = "form-control", @required = "required" })

    </div>





    <div class="form-group">
        <input type="submit" value="Guardar" class="btn btn-success" />

    </div>


}